# Home
title: Kanz's Blog

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  87kangsw

# Build settings
markdown: kramdown
remote_theme: chesterhow/tale

permalink:  /:year-:month-:day/:title
paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist

# To enable google analytics, supply your token below
analytics-google: UA-91948401-1

email: 87kangsw@gmail.com
facebook: sungwook.kang.923
github: 87kangsw
instagram: 87kangsw

authors:
    kanz:
        name: Kanz
        bio: iOS, iOS Developer
        external-image: false
        picture: assets/images/profile.jpg
        email: 87kangsw@gmail.com

